import test from 'node:test';
import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Processes} from '../src/processes.mjs';
const exec=promisify(execFile);
const cli=path.resolve(import.meta.dirname,'../bin/bridge.mjs');
const run=(args,options={})=>exec(process.execPath,[cli,...args],{timeout:20000,maxBuffer:65536,...options});
test('version is a preview, not a general availability claim',async()=>assert.match((await run(['version'])).stdout,/0\.1\.0-preview\.2/));
test('help does not enable a connection',async()=>assert.match((await run([])).stdout,/free local evaluation/));
test('local-access flag is required before tools can be served',async()=>{await assert.rejects(run(['serve']),error=>error.code===1&&error.stderr.includes('--allow-local-access'));});
test('unknown command fails instead of starting an agent',async()=>{await assert.rejects(run(['oops']),error=>error.code===1);});
test('config is explicit and includes no remote targets or credential',async()=>{const {stdout}=await run(['config']);const config=JSON.parse(stdout);const bridge=config.mcpServers['ganado-bridge'];assert.deepEqual(bridge.args,[cli,'serve','--allow-local-access']);assert.equal(bridge.command,process.execPath);assert.ok(!Object.hasOwn(bridge,'env'));});
test('real subprocess MCP selftest has eight verifiable outcomes',async()=>{const {stdout}=await run(['selftest']);const report=JSON.parse(stdout);assert.equal(report.passed,true);assert.equal(report.checks.length,8);});
test('no configured SSH targets by default',async t=>{const p=new Processes();t.after(()=>p.close());assert.equal(p.sshAliases.size,0);await assert.rejects(p.start({command:'printf NO',target:'not-configured'}),/not configured/);});
test('nonzero exit is preserved',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'bridge-exit-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const p=new Processes();t.after(()=>p.close());const job=await p.start({command:'printf TEST_ERROR; exit 7',cwd:root,wait_ms:500});const result=await p.read({session_id:job.session_id,wait_ms:500});assert.equal(result.exit_code,7);assert.equal(result.output,'TEST_ERROR');});
test('output truncation remains explicit',async t=>{const p=new Processes({maxCaptureBytes:16});t.after(()=>p.close());const job=await p.start({command:'printf 012345678901234567890123456789',wait_ms:500});const result=await p.read({session_id:job.session_id,offset:0,wait_ms:500});assert.equal(result.output,'4567890123456789');assert.ok(result.omitted_bytes>0);});
test('invalid configured SSH alias fails before serving',async()=>{await assert.rejects(run(['serve','--allow-local-access'],{env:{PATH:process.env.PATH,HOME:os.tmpdir(),BRIDGE_AGENT_SSH_ALIASES:'bad alias'}}),error=>error.code===1&&error.stderr.includes('Invalid SSH alias'));});
